name: LaTeX Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-full
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
